baseURL = "/"
title = "OpAMP Commander"

# Language settings
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Highlight settings
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsUseClassic = false
pygmentsStyle = "monokai"

# Content
contentDir = "content"
enableRobotsTXT = true
enableGitInfo = true

# Disable kinds we don't need
disableKinds = ["taxonomy"]

# Use Hugo modules
[module]
  proxy = "direct"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
    lineNos = false
    noClasses = false

# Site parameters
[params]
  description = "OpAMP Commander Documentation"
  copyright = "OpAMP Commander"
  
  # Enable offline search
  offlineSearch = true
  
  # Enable Mermaid diagrams
  mermaid.enable = true
  
  # UI customization
  [params.ui]
    sidebar_menu_compact = false
    sidebar_menu_foldable = true
    breadcrumb_disable = false
    navbar_logo = true
    sidebar_search_disable = false
    navbar_translucent_over_cover_disable = true
    showLightDarkModeMenu = true
    
  [params.ui.feedback]
    enable = true
    
  [params.ui.readingtime]
    enable = false
    
  # Links configuration
  [params.links]
    [[params.links.user]]
      name = "GitHub"
      url = "https://github.com/minuk-dev/opampcommander"
      icon = "fab fa-github"
      desc = "Development takes place here!"
    [[params.links.user]]
      name = "Email"
      url = "mailto:minuk.dev@gmail.com"
      icon = "fa fa-envelope"
      desc = "Discuss development issues around the project"

# Menu configuration
[menu]
  [[menu.main]]
    name = "Documentation"
    weight = 10
    url = "/en/docs/"
    
  [[menu.main]]
    name = "GitHub"
    weight = 50
    url = "https://github.com/minuk-dev/opampcommander"

# Language configuration
[languages]
  [languages.en]
    title = "OpAMP Commander"
    languageName = "English"
    weight = 1
